### ISSUE TITLE
Add support for more variations of the OMR sheet design

### ISSUE THREAD

**Issue by shahabblouch** [iansan5653/open-mcr#29]
Can I use a different Design of OMR Sheet with this script. Can you help me in designing my custom design sheet as a consultant.

**Comment by iansan5653** [comment]
Hello, you can customize the sheet in some ways - for example, you can change the fonts of the headings and add text or logos anywhere you want outside of the bubbles. You can remove the signature and date areas and the instructions. You can also delete the light gray columns and the squares for handwriting text. 

Things you definitely should not do:

* move, delete, or add any circles
* move delete, or add any of the dark corner marks

So long as you don't modify the circles or corner marks, the sheet should still scan correctly.

Please keep in mind that the sheet is licensed under CC BY-NC-SA 4.0, which means you are free to modify and redistribute it, but you must attribute the original project and share it under the same license, and you can't use it for commercial purposes.

Also, I can't guarantee that the program will work as well for modified sheets (and at this point, cannot speak for the reliability of the program at all since it is still in beta; it's ready to test but not to use in real-world environments).

**Comment by shahabblouch** [comment]
Hi, Thanks for detailed answer. I would like to work on this project , I appreciate your effort. I am new to python but found it very interesting. Today, I integrated your code with api using flask framework and would like to continue on it.
But I need 100 bubbles for answer is there anyway to add 25 more bubbles in it.

**Comment by iansan5653** [comment]
That would be great! Your contributions would be greatly appreciated. Let me know if you have any questions.

Unfortunately, adding more bubbles would not be possible without significantly modifying the code. When we first designed it we tried to get to 100 bubbles, but without using a different paper size (ie legal size) it would be very difficult to lay it out well. Adding support for a legal-sized PDF with 100 questions would be a great feature to consider for the future though. Or maybe a PDF of the same size but without the name fields and with more questions.

**Comment by shahabblouch** [comment]
Thanks, For your quick reply.
What if we removed following sections name,course. And placed barcode or QRcode. So every answer sheet will be unique and student specific. and we will be able to place more bubbles and increase their size too.

**Comment by iansan5653** [comment]
Adding some sort of barcode generator and reader might be a bit too much complexity, but even if we removed everything but the 10-digit Student ID, there would be enough numbers to make 10,000,000,000 unique sheets. Then the only code changes needed would be to remove the parts for the deleted fields and modify the definitions in `code/grid_info.py`.

I'll be offline starting tomorrow for about two weeks for vacation, but once I get back I will respond to any new questions.

**Comment by shahabblouch** [comment]
Thank you. 
Wish you a wonderful trip, rest a lot and have lots of fun.

**Comment by sqylogin** [comment]
I would also love to have the option for a different design. I'm hoping to extend the space available for names, use only one box for the middle initial, and reduce Student and course ID number.

**Comment by iansan5653** [comment]
@sqylogin Thanks for your feedback! Given the amount of interest in this feature, I will definitely look into it more. Allowing any sheet design would add a significant amount of complexity, but it's possible I could add a couple of variations on the existing design.

**Comment by iansan5653** [comment]
Hey @shahabblouch and @sqylogin, I am releasing a version now that supports an additional exam variant with space for 150 questions. I think this is all the variants I'm going to support for now; the amount of time required is not worth developing more variations as these two should address almost all use-cases.
