### ISSUE TITLE
Incorrect extracted data

### ISSUE THREAD

**Issue by LamassuSys** [iansan5653/open-mcr#36]
Greetings,
when I use some images, the program extracts incorrect data. 
Please see the attached images.
Thanks
Ammar

![0027](https://user-images.githubusercontent.com/40268405/120065905-6cdf8e00-c07c-11eb-89db-ee5249838751.jpg)
![0030](https://user-images.githubusercontent.com/40268405/120065929-8b458980-c07c-11eb-97d3-9b635c831750.jpg)
![0032](https://user-images.githubusercontent.com/40268405/120065946-a87a5800-c07c-11eb-9336-797589339f94.jpg)
![0001](https://user-images.githubusercontent.com/40268405/120065785-d4490e00-c07b-11eb-8c28-d90efccd0898.jpg)
![0014](https://user-images.githubusercontent.com/40268405/120065803-f2167300-c07b-11eb-8623-1546ebb9746a.jpg)
![0016](https://user-images.githubusercontent.com/40268405/120065823-11ad9b80-c07c-11eb-8a40-c12a1a848c07.jpg)
![0019](https://user-images.githubusercontent.com/40268405/120065857-30ac2d80-c07c-11eb-8922-c3ab324f5120.jpg)
![0026](https://user-images.githubusercontent.com/40268405/120065886-52a5b000-c07c-11eb-9901-f68da71f8276.jpg)

**Comment by iansan5653** [comment]
Thanks for the report. I'm able to replicate the problem and it's definitely concerning. I'll try to resolve it in the next few days.

**Comment by iansan5653** [comment]
Hi @LamassuSys, unfortunately I may not be able to fix this soon because I am busy with other projects and it looks like a complex problem. I think the root of the issue is some distortion in the scans. I recommend trying a different scanner for now, and I will plan on finding a solution in the next month or so.

**Comment by LamassuSys** [comment]
Okay,
thanks

**Comment by iansan5653** [comment]
Hello again @LamassuSys. I've just released v1.1.0, which you can download from https://github.com/iansan5653/open-mcr/releases. This version has many improvements to the grid finding algorithm and gets better results with your image. 

However, the results still aren't perfect. The problem is that the software establishes a grid based on the four corner marks and then reads bubbles from locations in the grid. Your images have some distortion that causes some of the bubbles to appear offset, outside of their expected location. You can see that in this image which renders the gridded circles over the data: 
![image](https://user-images.githubusercontent.com/2294248/140011182-7d8a9602-5a69-4059-b5b9-eed10c616df4.png)

Even though the corners are established precisely, the software cannot accurately read the bubbles because of the distortion. Unfortunately there is no feasible way to write an algorithm that can handle distortion like this - I recommend using a quality scanner and avoiding phone/camera images.
