### ISSUE TITLE
add 100 and 200 question sets also..

### ISSUE THREAD

**Issue by arindam25119325** [iansan5653/open-mcr#68]
add 100 and 200 question sets also..

**Comment by iansan5653** [comment]
Hi, thanks for the request. For the 100-question request, why not use the 150-question variant and leave the last 50 questions blank?

The 200-question request is challenging because there is simply not enough room on the paper to add many more questions beyond the 150 we already have. I think you could instead work around this by having students fill out two exam sheets. You could use test form code `A` for the first page and form code `B` for the second page, and then after processing use Excel to combine student's scores by matching their ID.

**Comment by iansan5653** [comment]
I'm going to close this for now. Feel free to reopen if you want to discuss further.
