### ISSUE TITLE
Add 200question option? 

### ISSUE THREAD

**Issue by georgebrianb** [iansan5653/open-mcr#71]
Hey, how long would it take to alter the script for a test with 200 questions? I am trying to prepare a simulation exam for medical students (offered for free) and the exam is a 200 questions one.

I would appreciate and try and help with this feature (I'm a linux engineer, but I'm trying to learn some OpenCV anyway)

**Comment by iansan5653** [comment]
Hi, I get a lot of requests for different form sizes but unfortunately it is pretty challenging to add new ones. The problem is not so much in the code (the code is generic enough that it's easy), it's with the sheet design - there's just not much more space for 50 more questions since we still need room for some sort of student identifier.

I think a better solution than packing more questions into the page at this point would be to add more pages. There is no software support for multiple pages (if you want to work on that it would be greatly appreciated!) but in the meantime what you could do is utilize the **Test Form Code** or the **Course ID** fields on the existing 150 question sheet.

For example, to give a two page exam, allowing for 150 questions:
1. On the first page, students would put their ID number and a test form code of `A`.
2. On the second page, students would put the same ID number and a test form code of `B`.
3. When scoring, you'd have to perform some data manipulation to link the pages together. You could split the results into two files, one with form code `A` and the other with form code `B`, then combine the results by matching the student ID.

**Comment by georgebrianb** [comment]
Hey, it's totally understandable, I will look through the code to see if I can manage to turn it into a student id-less option. I don't care as much about the test ID or the user ID. But hey, your work is amazing, what you've done here probably helps thousands of students and teachers!

**Comment by iansan5653** [comment]
Hi @georgebrianb, if you are still working on this please let me know and I will reopen it!
